<template>
    <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="currentColor"
        id="XMLID_276_"
        viewBox="0 0 24 24"
        xml:space="preserve"
    >
        <g id="contact-us">
            <g>
                <path d="M4,24v-5H0V0h23v19h-9.3L4,24z M2,17h4v3.7l7.3-3.7H21V2H2V17z" />
            </g>
            <g>
                <rect
                    x="5"
                    y="8"
                    width="3"
                    height="3"
                />
            </g>
            <g>
                <rect
                    x="10"
                    y="8"
                    width="3"
                    height="3"
                />
            </g>
            <g>
                <rect
                    x="15"
                    y="8"
                    width="3"
                    height="3"
                />
            </g>
        </g>
    </svg>
</template>
