import NotFound from '@/pages/not-found/not-found.vue'
import { createRouter, createWebHistory } from 'vue-router'

import ComingSoon from '@/shared/components/сoming-soon.vue'
import { ROUTE_PATHS } from '@/shared/configs/routes/routes'

export const router = createRouter({
    history: createWebHistory(),
    routes: [
        { path: ROUTE_PATHS.SSL.path, name: ROUTE_PATHS.SSL.name, component: ComingSoon },
        { path: ROUTE_PATHS.VOLUMES.path, name: ROUTE_PATHS.VOLUMES.name, component: ComingSoon },
        { path: ROUTE_PATHS.NETWORKS.path, name: ROUTE_PATHS.NETWORKS.name, component: ComingSoon },
        { path: ROUTE_PATHS.FWAAS.path, name: ROUTE_PATHS.FWAAS.name, component: ComingSoon },
        { path: ROUTE_PATHS.SECURITY_GROUPS.path, name: ROUTE_PATHS.SECURITY_GROUPS.name, component: ComingSoon },
        { path: ROUTE_PATHS.IMAGES.path, name: ROUTE_PATHS.IMAGES.name, component: ComingSoon },
        { path: ROUTE_PATHS.BACKUPS.path, name: ROUTE_PATHS.BACKUPS.name, component: ComingSoon },
        { path: ROUTE_PATHS.FILE_STORAGE.path, name: ROUTE_PATHS.FILE_STORAGE.name, component: ComingSoon },
        {
            path: ROUTE_PATHS.SERVERS_ORDER_PRE_BUILT.path,
            name: ROUTE_PATHS.SERVERS_ORDER_PRE_BUILT.name,
            component: () => import('@/pages/servers/servers-page.vue'),
        },
        { path: ROUTE_PATHS.SERVERS_COLOCATION.path, name: ROUTE_PATHS.SERVERS_COLOCATION.name, component: ComingSoon },
        { path: ROUTE_PATHS.SERVERS_RACKS.path, name: ROUTE_PATHS.SERVERS_RACKS.name, component: ComingSoon },
        { path: ROUTE_PATHS.SERVERS_NETWORKS.path, name: ROUTE_PATHS.SERVERS_NETWORKS.name, component: ComingSoon },
        { path: ROUTE_PATHS.SERVERS_BACKUP.path, name: ROUTE_PATHS.SERVERS_BACKUP.name, component: ComingSoon },
        { path: ROUTE_PATHS.SHD_BLOCK_STORAGE_DISKS.path, name: ROUTE_PATHS.SHD_BLOCK_STORAGE_DISKS.name, component: ComingSoon },
        { path: ROUTE_PATHS.BASIC_FIREWALL.path, name: ROUTE_PATHS.BASIC_FIREWALL.name, component: ComingSoon },
        { path: ROUTE_PATHS.NETWORK_EQUIPMENT_HOME.path, name: ROUTE_PATHS.NETWORK_EQUIPMENT_HOME.name, component: ComingSoon },
        { path: ROUTE_PATHS.ADDITIONAL_PORTS.path, name: ROUTE_PATHS.ADDITIONAL_PORTS.name, component: ComingSoon },
        { path: ROUTE_PATHS.SSH.path, name: ROUTE_PATHS.SSH.name, component: ComingSoon },
        { path: ROUTE_PATHS.DOCS.path, name: ROUTE_PATHS.DOCS.name, component: ComingSoon },
        { path: ROUTE_PATHS.GLOBAL_ROUTER.path, name: ROUTE_PATHS.GLOBAL_ROUTER.name, component: ComingSoon },
        { path: ROUTE_PATHS.NETWORK_IPAM.path, name: ROUTE_PATHS.NETWORK_IPAM.name, component: ComingSoon },
        { path: ROUTE_PATHS.NETWORK_BLOCKTOOLS_ATTACKS.path, name: ROUTE_PATHS.NETWORK_BLOCKTOOLS_ATTACKS.name, component: ComingSoon },
        { path: ROUTE_PATHS.NETWORK_ANTIDDOS.path, name: ROUTE_PATHS.NETWORK_ANTIDDOS.name, component: ComingSoon },
        { path: ROUTE_PATHS.NETWORK_LOAD_BALANCER.path, name: ROUTE_PATHS.NETWORK_LOAD_BALANCER.name, component: ComingSoon },
        { path: ROUTE_PATHS.VPC_LICENSES.path, name: ROUTE_PATHS.VPC_LICENSES.name, component: ComingSoon },
        { path: ROUTE_PATHS.QUOTAS.path, name: ROUTE_PATHS.QUOTAS.name, component: ComingSoon },
        { path: ROUTE_PATHS.SECURITY_CERTIFIED_SERVERS.path, name: ROUTE_PATHS.SECURITY_CERTIFIED_SERVERS.name, component: ComingSoon },
        { path: ROUTE_PATHS.SECURITY_CERTIFIED_CLOUD.path, name: ROUTE_PATHS.SECURITY_CERTIFIED_CLOUD.name, component: ComingSoon },
        { path: ROUTE_PATHS.SECURITY_SERVER_PROTECTION.path, name: ROUTE_PATHS.SECURITY_SERVER_PROTECTION.name, component: ComingSoon },
        { path: ROUTE_PATHS.WR_DEFAULT_RESOURCES.path, name: ROUTE_PATHS.WR_DEFAULT_RESOURCES.name, component: ComingSoon },
        { path: ROUTE_PATHS.DNS_DEFAULT_HOSTING.path, name: ROUTE_PATHS.DNS_DEFAULT_HOSTING.name, component: ComingSoon },
        { path: ROUTE_PATHS.CDN.path, name: ROUTE_PATHS.CDN.name, component: ComingSoon },
        { path: ROUTE_PATHS.ML_DEFAULT_ML_PLATFORM.path, name: ROUTE_PATHS.ML_DEFAULT_ML_PLATFORM.name, component: ComingSoon },
        {
            path: ROUTE_PATHS.ML_DEFAULT_INFERENCE_PLATFORM.path,
            name: ROUTE_PATHS.ML_DEFAULT_INFERENCE_PLATFORM.name,
            component: ComingSoon,
        },
        { path: ROUTE_PATHS.ADMIN_DASHBOARD.path, name: ROUTE_PATHS.ADMIN_DASHBOARD.name, component: ComingSoon },
        { path: ROUTE_PATHS.ADMIN_USERS.path, name: ROUTE_PATHS.ADMIN_USERS.name, component: ComingSoon },
        { path: ROUTE_PATHS.ADMIN_ROLES.path, name: ROUTE_PATHS.ADMIN_ROLES.name, component: ComingSoon },
        { path: ROUTE_PATHS.ADMIN_PERMISSIONS.path, name: ROUTE_PATHS.ADMIN_PERMISSIONS.name, component: ComingSoon },
        { path: ROUTE_PATHS.ADMIN_SETTINGS.path, name: ROUTE_PATHS.ADMIN_SETTINGS.name, component: ComingSoon },
        { path: ROUTE_PATHS.ADMIN_SERVERS.path, name: ROUTE_PATHS.ADMIN_SERVERS.name, component: ComingSoon },
        { path: ROUTE_PATHS.ADMIN_CLOUD.path, name: ROUTE_PATHS.ADMIN_CLOUD.name, component: ComingSoon },
        { path: ROUTE_PATHS.ADMIN_NETWORK.path, name: ROUTE_PATHS.ADMIN_NETWORK.name, component: ComingSoon },
        { path: ROUTE_PATHS.ADMIN_SECURITY.path, name: ROUTE_PATHS.ADMIN_SECURITY.name, component: ComingSoon },
        { path: ROUTE_PATHS.ADMIN_LOGS.path, name: ROUTE_PATHS.ADMIN_LOGS.name, component: ComingSoon },
        { path: ROUTE_PATHS.ADMIN_PERFORMANCE.path, name: ROUTE_PATHS.ADMIN_PERFORMANCE.name, component: ComingSoon },
        { path: ROUTE_PATHS.ADMIN_REPORTS_USAGE.path, name: ROUTE_PATHS.ADMIN_REPORTS_USAGE.name, component: ComingSoon },
        { path: ROUTE_PATHS.ADMIN_REPORTS_FINANCIAL.path, name: ROUTE_PATHS.ADMIN_REPORTS_FINANCIAL.name, component: ComingSoon },
        { path: ROUTE_PATHS.MANAGER_DASHBOARD.path, name: ROUTE_PATHS.MANAGER_DASHBOARD.name, component: ComingSoon },
        { path: ROUTE_PATHS.MANAGER_SERVERS.path, name: ROUTE_PATHS.MANAGER_SERVERS.name, component: ComingSoon },
        { path: ROUTE_PATHS.MANAGER_CLOUD.path, name: ROUTE_PATHS.MANAGER_CLOUD.name, component: ComingSoon },
        { path: ROUTE_PATHS.MANAGER_NETWORK.path, name: ROUTE_PATHS.MANAGER_NETWORK.name, component: ComingSoon },
        { path: ROUTE_PATHS.MANAGER_REPORTS.path, name: ROUTE_PATHS.MANAGER_REPORTS.name, component: ComingSoon },
        { path: ROUTE_PATHS.MANAGER_REQUESTS.path, name: ROUTE_PATHS.MANAGER_REQUESTS.name, component: ComingSoon },
        { path: ROUTE_PATHS.DEVELOPER_API.path, name: ROUTE_PATHS.DEVELOPER_API.name, component: ComingSoon },
        { path: ROUTE_PATHS.DEVELOPER_DOCS.path, name: ROUTE_PATHS.DEVELOPER_DOCS.name, component: ComingSoon },
        { path: ROUTE_PATHS.DEVELOPER_ENVIRONMENTS_DEV.path, name: ROUTE_PATHS.DEVELOPER_ENVIRONMENTS_DEV.name, component: ComingSoon },
        { path: ROUTE_PATHS.DEVELOPER_ENVIRONMENTS_TEST.path, name: ROUTE_PATHS.DEVELOPER_ENVIRONMENTS_TEST.name, component: ComingSoon },
        { path: ROUTE_PATHS.DEVELOPER_ENVIRONMENTS_PROD.path, name: ROUTE_PATHS.DEVELOPER_ENVIRONMENTS_PROD.name, component: ComingSoon },
        { path: ROUTE_PATHS.DEVELOPER_DEPLOYMENT.path, name: ROUTE_PATHS.DEVELOPER_DEPLOYMENT.name, component: ComingSoon },
        { path: ROUTE_PATHS.DEVELOPER_MONITORING.path, name: ROUTE_PATHS.DEVELOPER_MONITORING.name, component: ComingSoon },
        { path: ROUTE_PATHS.GUEST_HOME.path, name: ROUTE_PATHS.GUEST_HOME.name, component: ComingSoon },
        { path: ROUTE_PATHS.GUEST_DOCS.path, name: ROUTE_PATHS.GUEST_DOCS.name, component: ComingSoon },
        { path: ROUTE_PATHS.GUEST_CONTACT.path, name: ROUTE_PATHS.GUEST_CONTACT.name, component: ComingSoon },
        {
            path: ROUTE_PATHS.LOGIN.path,
            name: ROUTE_PATHS.LOGIN.name,
            component: () => import('@/pages/login/login.vue'),
        },
        { path: ROUTE_PATHS.NOT_FOUND.path, name: ROUTE_PATHS.NOT_FOUND.name, component: NotFound },
    ],
})
